get http://localhost:5000/event-api/events

###

post http://localhost:5000/event-api/events
Content-Type: application/json

{

    "eventname":"VBS2024",
    "events":[]
}
###
get http://localhost:5000/event-api/years

###
get http://localhost:5000/event-api/events/2024
###
put http://localhost:5000/event-api/events/VBS 2024
Content-Type: application/json

{

    "events": ["event1","event2","event4"]
}

###
delete http://localhost:5000/event-api/events/ypannual2023

###
get http://localhost:5000/user-api/users

###
post http://localhost:5000/user-api/user
Content-Type: application/json

{
    "fullname":"nikhil",
    "username":"nikhil",
    "password":"nikhil",
    "email":"nikhil@gmail.com"
}

###
post http://localhost:5000/user-api/login
Content-Type: application/json

{
    
    "username":"Nikhil",
    "password":"nikhil"
   
}
