get https://salvation-army-pezzonipet-gn1u.vercel.app/event-api/events

###

post https://salvation-army-pezzonipet-gn1u.vercel.app/event-api/events
Content-Type: application/json

{

    "eventname":"VBS2024",
    "events":[]
}

###
put https://salvation-army-pezzonipet-gn1u.vercel.app/event-api/events/VBS 2024
Content-Type: application/json

{

    "events": ["event1","event2","event4"]
}

###
delete https://salvation-army-pezzonipet-gn1u.vercel.app/event-api/events/ypannual2023

###
get https://salvation-army-pezzonipet-gn1u.vercel.app/user-api/users

###
post https://salvation-army-pezzonipet-gn1u.vercel.app/user-api/user
Content-Type: application/json

{
    "fullname":"nikhil",
    "username":"nikhil",
    "password":"nikhil",
    "email":"nikhil@gmail.com"
}

###
post https://salvation-army-pezzonipet-gn1u.vercel.app/user-api/login
Content-Type: application/json

{
    
    "username":"Nikhil",
    "password":"nikhil"
   
}
